# Generated by Django 4.0 on 2023-04-18 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('release_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='albums_images')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('genre', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='artist_images')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist_Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='playlist_images')),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('path', models.FileField(null=True, upload_to='music')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.albums')),
                ('playlists_tr', models.ManyToManyField(through='Music.Playlist_Tracks', to='Music.Playlists')),
            ],
        ),
        migrations.AddField(
            model_name='playlists',
            name='tracks_pl',
            field=models.ManyToManyField(through='Music.Playlist_Tracks', to='Music.Tracks'),
        ),
        migrations.AddField(
            model_name='playlists',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.customuser'),
        ),
        migrations.AddField(
            model_name='playlist_tracks',
            name='playlist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.playlists'),
        ),
        migrations.AddField(
            model_name='playlist_tracks',
            name='track_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.tracks'),
        ),
        migrations.AddField(
            model_name='albums',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.artist'),
        ),
        migrations.AddConstraint(
            model_name='playlist_tracks',
            constraint=models.UniqueConstraint(fields=('playlist_id', 'track_id'), name='unique_track_playlist'),
        ),
    ]
