# Generated by Django 4.0 on 2023-03-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist_track',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='playlist_track',
            name='playlist_id',
        ),
        migrations.AddField(
            model_name='playlist_track',
            name='playlist_id',
            field=models.ManyToManyField(to='Music.Playlist'),
        ),
    ]
