# Generated by Django 4.0 on 2023-03-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_playlist_track_id_remove_playlist_track_playlist_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist_track',
            name='music_id',
        ),
        migrations.RemoveField(
            model_name='playlist_track',
            name='playlist_id',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='Playlist_track',
        ),
    ]
