# Generated by Django 4.0 on 2023-03-27 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Music', '0003_remove_playlist_track_music_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist_Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.music')),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.playlist')),
            ],
        ),
    ]
