# Generated by Django 4.0 on 2023-04-17 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0004_playlist_playlist_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritemusic',
            name='music',
        ),
        migrations.RemoveField(
            model_name='favoritemusic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='music',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='playlist_track',
            name='music_id',
        ),
        migrations.RemoveField(
            model_name='playlist_track',
            name='playlist_id',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='FavoriteMusic',
        ),
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='Playlist_Track',
        ),
    ]
