# Generated by Django 3.2 on 2023-03-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20230319_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='colors',
        ),
    ]
