# Generated by Django 3.2 on 2023-03-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_remove_music_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='colors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='settings.color'),
            preserve_default=False,
        ),
    ]
