# Generated by Django 3.2 on 2023-03-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_music_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='colors',
        ),
    ]
