# Generated by Django 3.2 on 2023-03-19 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_remove_music_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='music',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='settings.music'),
            preserve_default=False,
        ),
    ]
