# Generated by Django 3.2 on 2023-03-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_color_music'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
