# Generated by Django 3.2 on 2023-03-19 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_color', to='settings.music'),
        ),
    ]
